version: '3'

services:
  llm-shell:
    container_name: llm-shell
    build: .
    ports:
      - "5220:5220"
    env_file:
      - .env
    environment:
      - OLLAMA_API_URL=${OLLAMA_API_URL}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME}
      - OLLAMA_TEMPERATURE=${OLLAMA_TEMPERATURE}
      - OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH}
      - MAX_COMMANDS=${MAX_COMMANDS}
      - TIMEOUT_SECONDS=${TIMEOUT_SECONDS}
      - FLASK_PORT=5220
      - FLASK_HOST=0.0.0.0
      - FLASK_DEBUG=${FLASK_DEBUG:-False}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///app/data/llm_shell.db}
    volumes:
      - ./app/data:/app/data